### ISSUE TITLE
Issue with Uinavigation Background image

### ISSUE THREAD

**Issue by veerairvalid** [boctor/idev-recipes#10]
hello everyone, i am using the example where we have custom UINavigation background image :

[customNavigationBar setBackgroundWith:[UIImage imageNamed:@"navigationBarBackgroundRetro.png"]];

I have created a Uinavigation Bar project and imported the required files. i am getting the following error :

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UINavigationBar setBackgroundWith:]: unrecognized selector sent to instance.

Many thanks :)

**Comment by veerairvalid** [comment]
its working in fact i forgot to set the class of the  navigation controller to customNavigationbar. its working now thanks :)

**Comment by LiLejia** [comment]
Hey, buddy, it seem like I got the same problem with you. Apparently you solved the problem, but I still didn't get what do you mean by 'set the class of the navigation controller to customNavigationbar' 
if it is CustomNavigationBar\* customNavigationBar = (CustomNavigationBar*)(self.navigationController.navigationBar); I certainly did it;
But the Example linked the mainWindow's navigationController with IBOutlet UINavigationController and its delegate, how could I implement by just code in a individual view instead of a RootViewController

So would you help me out?

**Comment by victorguo** [comment]
UIViewController *viewController = [[UIViewController alloc] init];
UINavigationController *navigationController = [[UINavigationController alloc] initWithNavigationBarClass:[CustomNavigationBar class] toolbarClass:nil];
[navigationController setViewControllers:[NSMutableArray arrayWithObjects:viewController, nil]];

CustomNavigationBar\* customNavigationBar = (CustomNavigationBar*)navigationController.navigationBar;
[customNavigationBar setBackgroundWith:[UIImage imageNamed:@"navigation_bar"]];

**Comment by ZuzooVn** [comment]
Hey @victorguo , i tried your code and have this error:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UINavigationController initWithNavigationBarClass:toolbarClass:]: unrecognized selector sent to instance 0x150bf0'

How can i fix it?

Thanks you

**Comment by victorguo** [comment]
@ZuzooVn Which iOS version are you developing with? **initWithNavigationBarClass:toolbarClass:** is available in iOS 5.0 and later.

Or could you show me your complete project?
